server.port=8080
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/gtf_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
##(create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update
jwt.secret-key=+T+oFFUUml+UVhByeSzZmpqO3O9Vk78jYYcBTPkXkoyNcubm3wos7pxttUhVxkpgxnf/rUrgsinuZqYrptO9tjY3XGJim6KJLRlm8S6yywAzmFVdLCgRqBMkYfgzrINjO7seLzsnbiESlB0INh6RMu40Pv8nyLQVXKagNGaDwingojD0jf7zWgXEwCwJK9HvS5KOgjoWQbGrjfw4pP1FSN6IHtJIMdmf3HvzoDVPcyPejc/6SH4xqyJV7GC9qy3hV9EDa8m9OFmCKy8wLdcyKelpLvRpeY1lL/MFrjVcJV+nSR8eysFtzy6LVbXrni5wkY8x5UykzXZ1lMWcJYJXO2tvPyraX+YB0xSfXCsCwi0=
